#! /usr/bin/env python
#| This file is a part of the sferes2 framework.
#| Copyright 2009, ISIR / Universite Pierre et Marie Curie (UPMC)
#| Main contributor(s): Jean-Baptiste Mouret, mouret@isir.fr
#|
#| This software is a computer program whose purpose is to facilitate
#| experiments in evolutionary computation and evolutionary robotics.
#| 
#| This software is governed by the CeCILL license under French law
#| and abiding by the rules of distribution of free software.  You
#| can use, modify and/ or redistribute the software under the terms
#| of the CeCILL license as circulated by CEA, CNRS and INRIA at the
#| following URL "http://www.cecill.info".
#| 
#| As a counterpart to the access to the source code and rights to
#| copy, modify and redistribute granted by the license, users are
#| provided only with a limited warranty and the software's author,
#| the holder of the economic rights, and the successive licensors
#| have only limited liability.
#|
#| In this respect, the user's attention is drawn to the risks
#| associated with loading, using, modifying and/or developing or
#| reproducing the software by the user in light of its specific
#| status of free software, that may mean that it is complicated to
#| manipulate, and that also therefore means that it is reserved for
#| developers and experienced professionals having in-depth computer
#| knowledge. Users are therefore encouraged to load and test the
#| software's suitability as regards their requirements in conditions
#| enabling the security of their systems and/or data to be ensured
#| and, more generally, to use and operate it in the same conditions
#| as regards security.
#|
#| The fact that you are presently reading this means that you have
#| had knowledge of the CeCILL license and that you accept its terms.




import os

def set_options(blah) : pass

def configure(blah): pass

def build(bld):
    print ("Entering directory `" + os.getcwd() + "/modules/'")
    test_nn = bld.new_task_gen('cxx', 'program')
    test_nn.source = 'test_nn.cpp'
    test_nn.includes = '. ../../'
    test_nn.uselib_local = ''
    test_nn.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK'
    test_nn.target = 'test_nn'
    test_nn.unit_test = 1

    test_dnn = bld.new_task_gen('cxx', 'program')
    test_dnn.source = 'test_dnn.cpp'
    test_dnn.includes = '. ../../'
    test_dnn.uselib_local = 'sferes2'
    test_dnn.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK BOOST_SERIALIZATION'
    test_dnn.target = 'test_dnn'
    test_dnn.unit_test = 1

    test_mlp = bld.new_task_gen('cxx', 'program')
    test_mlp.source = 'test_mlp.cpp'
    test_mlp.includes = '. ../../'
    test_mlp.uselib_local = 'sferes2'
    test_mlp.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK BOOST_SERIALIZATION'
    test_mlp.target = 'test_mlp'
    test_mlp.unit_test = 1

    test_esn = bld.new_task_gen('cxx', 'program')
    test_esn.source = 'test_hyper_nn.cpp'
    test_esn.includes = '. ../../'
    test_esn.uselib_local = 'sferes2'
    test_esn.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK BOOST_SERIALIZATION'
    test_esn.target = 'test_hyper_nn'
    test_esn.unit_test = 1


    test_esn = bld.new_task_gen('cxx', 'program')
    test_esn.source = 'test_dnn_ff.cpp'
    test_esn.includes = '. ../../'
    test_esn.uselib_local = 'sferes2'
    test_esn.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK BOOST_SERIALIZATION'
    test_esn.target = 'test_dnn_ff'
    test_esn.unit_test = 1



    test_osc = bld.new_task_gen('cxx', 'program')
    test_osc.source = 'test_osc.cpp'
    test_osc.includes = '. ../../'
    test_osc.uselib_local = 'sferes2'
    test_osc.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK BOOST_SERIALIZATION'
    test_osc.target = 'test_osc'
    test_osc.unit_test = 1


    bench_nn = bld.new_task_gen('cxx', 'program')
    bench_nn.source = 'bench_nn.cpp'
    bench_nn.includes = '. ../../'
    bench_nn.uselib_local = 'sferes2'
    bench_nn.uselib = 'EIGEN3 BOOST_GRAPH BOOST'
    bench_nn.target = 'bench_nn'
    
    # Added tests by Anh --------------------------------------------------------------------
    test_esn = bld.new_task_gen('cxx', 'program')
    test_esn.source = 'test_hyper_nn_anh.cpp'
    test_esn.includes = '. ../../'
    test_esn.uselib_local = 'sferes2'
    test_esn.uselib = 'EIGEN3 BOOST BOOST_GRAPH BOOST_UNIT_TEST_FRAMEWORK BOOST_SERIALIZATION'
    test_esn.target = 'test_hyper_nn_anh'
    test_esn.unit_test = 1

