// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.

#ifndef OPENCV_QUALITYBASE_HPP
#define OPENCV_QUALITYBASE_HPP

#include <vector>
#include <opencv2/core.hpp>

namespace cv
{
	namespace quality
	{
        /** @brief Type of output quality maps (if generated by the algorithm) */
        using quality_map_type = UMat;

		/************************************ Quality Base Class ************************************/

		class CV_EXPORTS_W QualityBase
            : public virtual Algorithm
		{
		public:

            /**
			@brief Destructor
			 */
			virtual ~QualityBase() = default;

            /**
            @brief
            @param cmpImgs comparison image(s), can be empty for no-reference quality algorithms
            */
            virtual CV_WRAP cv::Scalar compute( InputArrayOfArrays cmpImgs ) = 0;

            /** @brief Returns pointer to output quality maps images that were generated during computation, if supported by the algorithm.  */
            virtual CV_WRAP const std::vector<quality_map_type>& getQualityMaps() const = 0;
		};
	}
}
#endif