#OPENCV_LOC=/home/elchaschab/devel/opencv/
#FFMPEG_LOC=/home/elchaschab/devel/cartwheel-ffmpeg/ffmpeg/
#export LD_LIBRARY_PATH="$OPENCV_LOC/build/lib/:$FFMPEG_LOC/libavcodec/:$FFMPEG_LOC/libavutil/:$FFMPEG_LOC/libavdevice/:$FFMPEG_LOC/libavformat/:$FFMPEG_LOC/libavfilter/:$FFMPEG_LOC/libpostproc/:$FFMPEG_LOC/libswresample/:$FFMPEG_LOC/libswscale/:$LD_LIBRARY_PATH"

export OPENCV_LOG_LEVEL=VERBOSE
export OPENCV_FFMPEG_LOGLEVEL=56
export OPENCV_VIDEOIO_DEBUG=1
export OPENCV_VIDEOWRITER_DEBUG=1
export OPENCV_VIDEOCAPTURE_DEBUG=1
export OPENCV_FFMPEG_DEBUG=1
export OPENCV_OPENCL_RAISE_ERROR=1
export OPENCV_OPENCL_ABORT_ON_BUILD_ERROR=1
export OPENCV_DUMP_ERRORS=1
export OPENCV_DUMP_CONFIG=1
export OPENCV_TRACE=1
export OPENCV_TRACE_DEPTH_OPENCV=1
export OPENCV_TRACE_SYNC_OPENCL=1
#export OPENCV_CPU_DISABLE=
#export OPENCV_OPENCL_ENABLE_MEM_USE_HOST_PTR=1
#export OPENCV_OPENCL_ALIGNMENT_MEM_USE_HOST_PTR=1
#export OPENCV_OPENCL_RUNTIME=
#export OPENCV_OPENCL_DEVICE=
#export OPENCV_OPENCL_SVM_DISABLE=1

