#! /usr/bin/env python    
def build(bld):    
    return None
    # ex_ea
    #obj = bld.new_task_gen('cxx', 'program')
    #obj.source = 'ex_ea.cpp'
    #obj.includes = '../'
    #obj.target = 'ex_ea'
    #obj.uselib_local = 'sferes2'
    #obj.uselib = 'TBB BOOST BOOST_UNIT_TEST_FRAMEWORK EIGEN3'

    ## ex_ea
    #obj = bld.new_task_gen('cxx', 'program')
    #obj.source = 'ex_ea_mpi.cpp'
    #obj.includes = '../'
    #obj.target = 'ex_ea_mpi'
    #obj.uselib_local = 'sferes2'
    #obj.uselib = 'TBB BOOST BOOST_UNIT_TEST_FRAMEWORK EIGEN3'

    ## ex_nsga2
    #obj = bld.new_task_gen('cxx', 'program')
    #obj.source = 'ex_nsga2.cpp'
    #obj.includes = '../'
    #obj.target = 'ex_nsga2'
    #obj.uselib_local = 'sferes2'
    #obj.uselib = 'TBB BOOST BOOST_UNIT_TEST_FRAMEWORK EIGEN3'

    ## ex_eps_moea
    #obj = bld.new_task_gen('cxx', 'program')
    #obj.source = 'ex_eps_moea.cpp'
    #obj.includes = '../'
    #obj.target = 'ex_eps_moea'
    #obj.uselib_local = 'sferes2'
    #obj.uselib = 'TBB BOOST BOOST_UNIT_TEST_FRAMEWORK EIGEN3'
