/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_sample_app_NativeClass */

#ifndef _Included_org_opencv_sample_app_NativeClass
#define _Included_org_opencv_sample_app_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    EstimatePoseArucoMarker
 * Signature: (JLorg/opencv/sample/containers/Parameters;Lorg/opencv/sample/containers/CameraMatrix;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_EstimatePoseArucoMarker
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    EstimatePoseArucoBoard
 * Signature: (JLorg/opencv/sample/containers/Parameters;Lorg/opencv/sample/containers/CameraMatrix;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_EstimatePoseArucoBoard
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    EstimatePoseCharucoBoard
 * Signature: (JLorg/opencv/sample/containers/Parameters;Lorg/opencv/sample/containers/CameraMatrix;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_EstimatePoseCharucoBoard
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    EstimatePoseCharucoDiamond
 * Signature: (JLorg/opencv/sample/containers/Parameters;Lorg/opencv/sample/containers/CameraMatrix;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_EstimatePoseCharucoDiamond
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    CalibrateCameraCharucoBoard
 * Signature: (Lorg/opencv/sample/containers/Parameters;Lorg/opencv/sample/containers/CameraMatrix;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_CalibrateCameraCharucoBoard
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    CalibrateCameraArucoBoard
 * Signature: (Lorg/opencv/sample/containers/Parameters;Lorg/opencv/sample/containers/CameraMatrix;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_CalibrateCameraArucoBoard
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    SendCalibrationImage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_SendCalibrationImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_opencv_sample_app_NativeClass
 * Method:    ResetCalibration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_app_NativeClass_ResetCalibration
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
