/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_sample_cube3d_NativeClass */

#ifndef _Included_org_opencv_sample_cube3d_NativeClass
#define _Included_org_opencv_sample_cube3d_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_sample_cube3d_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_cube3d_NativeClass_getStringFromNative
  (JNIEnv * env, jobject obj);

/*
 * Class:     org_opencv_sample_cube3d_NativeClass
 * Method:    getStringFromNative2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencv_sample_cube3d_NativeClass_getStringFromNative2
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
